### ISSUE TITLE
Flakey test: SuspendResumeOrchestration

### ISSUE THREAD

**Issue by cgillum** [microsoft/durabletask-go#19]
The integration test `SuspendResumeOrchestration` failed in a recent PR: https://github.com/microsoft/durabletask-go/actions/runs/5028545973/jobs/9019359366.

A re-run of the test passed, but integration and unit tests should pass 100% of the time.

Output logs for this particular test execution.

```
DEBUG: 2023/05/19 21:48:35 orchestration-processor: waiting for one of 1 in-flight execution(s) to complete
DEBUG: 2023/05/19 21:48:35 orchestration-processor: processing work item: 0[620](https://github.com/microsoft/durabletask-go/actions/runs/5028545973/jobs/9019359366?pr=17#step:5:621)03b7-9540-4a80-9188-724e83e9aee3 (3 event(s))
DEBUG: 2023/05/19 21:48:35 062003b7-9540-4a80-9188-724e83e9aee3: received work item with 3 new event(s): [ExecutionStarted, ExecutionSuspended, EventRaised]
DEBUG: 2023/05/19 21:48:35 activity-processor: waiting for new work items...
DEBUG: 2023/05/19 21:48:35 062003b7-9540-4a80-9188-724e83e9aee3: got orchestration runtime state: name=SuspendResumeOrchestration, status=PENDING, events=0, age=(new)
INFO: 2023/05/19 21:48:35 062003b7-9540-4a80-9188-724e83e9aee3: starting new 'SuspendResumeOrchestration' instance with ID = '062003b7-9540-4a80-9188-724e83e9aee3'.
DEBUG: 2023/05/19 21:48:35 062003b7-9540-4a80-9188-724e83e9aee3: invoking orchestrator
DEBUG: 2023/05/19 21:48:35 062003b7-9540-4a80-9188-724e83e9aee3: orchestrator returned 1 action(s): [CreateTimer#0]
DEBUG: 2023/05/19 21:48:35 orchestration-processor: work item processed successfully
DEBUG: 2023/05/19 21:48:35 orchestration-processor: waiting for one of 1 in-flight execution(s) to complete
DEBUG: 2023/05/19 21:48:35 orchestration-processor: processing work item: 062003b7-9540-4a80-9188-724e83e9aee3 (4 event(s))
DEBUG: 2023/05/19 21:48:35 062003b7-9540-4a80-9188-724e83e9aee3: received work item with 4 new event(s): [EventRaised, EventRaised, EventRaised, EventRaised]
DEBUG: 2023/05/19 21:48:35 062003b7-9540-4a80-9188-724e83e9aee3: got orchestration runtime state: name=SuspendResumeOrchestration, status=SUSPENDED, events=5, age=0s
DEBUG: 2023/05/19 21:48:35 062003b7-9540-4a80-9188-724e83e9aee3: invoking orchestrator
DEBUG: 2023/05/19 21:48:35 062003b7-9540-4a80-9188-724e83e9aee3: orchestrator returned 1 action(s): [CreateTimer#0]
DEBUG: 2023/05/19 21:48:35 orchestration-processor: work item processed successfully
DEBUG: 2023/05/19 21:48:35 orchestration-processor: waiting for one of 1 in-flight execution(s) to complete
DEBUG: 2023/05/19 21:48:35 orchestration-processor: processing work item: 062003b7-9540-4a80-9188-724e83e9aee3 (3 event(s))
DEBUG: 2023/05/19 21:48:35 062003b7-9540-4a80-9188-724e83e9aee3: received work item with 3 new event(s): [EventRaised, EventRaised, EventRaised]
DEBUG: 2023/05/19 21:48:35 062003b7-9540-4a80-9188-724e83e9aee3: got orchestration runtime state: name=SuspendResumeOrchestration, status=SUSPENDED, events=11, age=0s
DEBUG: 2023/05/19 21:48:35 062003b7-9540-4a80-9188-724e83e9aee3: invoking orchestrator
DEBUG: 2023/05/19 21:48:35 062003b7-9540-4a80-9188-724e83e9aee3: orchestrator returned 1 action(s): [CreateTimer#0]
INFO: 2023/05/19 21:48:35 orchestration-processor: received cancellation signal
INFO: 2023/05/19 21:48:35 orchestration-processor: stopped listening for new work items
DEBUG: 2023/05/19 21:48:35 orchestration-processor: work item processed successfully
DEBUG: 2023/05/19 21:48:35 orchestration-processor: waiting for one of 1 in-flight execution(s) to complete
DEBUG: 2023/05/19 21:48:35 orchestration-processor: processing work item: 062003b7-9540-4a80-9188-724e83e9aee3 (2 event(s))
DEBUG: 2023/05/19 21:48:35 062003b7-9540-4a80-9188-724e83e9aee3: received work item with 2 new event(s): [EventRaised, EventRaised]
DEBUG: 2023/05/19 21:48:35 062003b7-9540-4a80-9188-724e83e9aee3: got orchestration runtime state: name=SuspendResumeOrchestration, status=SUSPENDED, events=16, age=0s
DEBUG: 2023/05/19 21:48:35 062003b7-9540-4a80-9188-724e83e9aee3: invoking orchestrator
DEBUG: 2023/05/19 21:48:35 062003b7-9540-4a80-9188-724e83e9aee3: orchestrator returned 1 action(s): [CreateTimer#0]
DEBUG: 2023/05/19 21:48:35 orchestration-processor: work item processed successfully
DEBUG: 2023/05/19 21:48:35 orchestration-processor: waiting for new work items...
INFO: 2023/05/19 21:48:35 activity-processor: received cancellation signal
INFO: 2023/05/19 21:48:35 activity-processor: stopped listening for new work items
DEBUG: 2023/05/19 21:48:38 orchestration-processor: waiting for one of 1 in-flight execution(s) to complete
DEBUG: 2023/05/19 21:48:38 orchestration-processor: processing work item: 062003b7-9540-4a80-9188-724e83e9aee3 (1 event(s))
DEBUG: 2023/05/19 21:48:38 062003b7-9540-4a80-9188-724e83e9aee3: received work item with 1 new event(s): [ExecutionResumed]
DEBUG: 2023/05/19 21:48:38 062003b7-9540-4a80-9188-724e83e9aee3: got orchestration runtime state: name=SuspendResumeOrchestration, status=SUSPENDED, events=20, age=3s
DEBUG: 2023/05/19 21:48:38 062003b7-9540-4a80-9188-724e83e9aee3: invoking orchestrator
panic: a previous execution called CreateTimer with sequence number 0, but the current execution doesn't have this action with this sequence number [recovered]
	panic: a previous execution called CreateTimer with sequence number 0, but the current execution doesn't have this action with this sequence number

goroutine 1820 [running]:
github.com/microsoft/durabletask-go/task.(*OrchestrationContext).start.func1()
	/home/runner/work/durabletask-go/durabletask-go/task/orchestrator.go:83 +0xd8
panic({0xb927c0, 0xc0002fe2d0})
	/opt/hostedtoolcache/go/1.19.9/x64/src/runtime/panic.go:884 +0x212
github.com/microsoft/durabletask-go/task.(*completableTask).Await(0xc0002fd300, {0xb57420, 0xc0003c[628](https://github.com/microsoft/durabletask-go/actions/runs/5028545973/jobs/9019359366?pr=17#step:5:629)0})
	/home/runner/work/durabletask-go/durabletask-go/task/task.go:67 +0x225
github.com/microsoft/durabletask-go/tests.Test_SuspendResumeOrchestration.func1(0xba0340?)
	/home/runner/work/durabletask-go/durabletask-go/tests/orchestrations_test.go:534 +0x82
github.com/microsoft/durabletask-go/task.(*OrchestrationContext).onExecutionStarted(0xc0003f0100, 0xc0001acf50)
	/home/runner/work/durabletask-go/durabletask-go/task/orchestrator.go:284 +0x133
github.com/microsoft/durabletask-go/task.(*OrchestrationContext).processEvent(0xc0003f0100, 0x7fdc72de85b8?)
	/home/runner/work/durabletask-go/durabletask-go/task/orchestrator.go:144 +0x525
github.com/microsoft/durabletask-go/task.(*OrchestrationContext).processNextEvent(0x7fdc72de85b8?)
	/home/runner/work/durabletask-go/durabletask-go/task/orchestrator.go:106 +0x47
github.com/microsoft/durabletask-go/task.(*OrchestrationContext).start(0xc0003f0100)
	/home/runner/work/durabletask-go/durabletask-go/task/orchestrator.go:88 +0x125
github.com/microsoft/durabletask-go/task.(*taskExecutor).ExecuteOrchestrator(0xc0002fe2a0?, {0xc00011a010?, 0xc0001d4140?}, {0xc000317440, 0x24}, {0xc0003ee000, 0x14, 0x14}, {0xc0003ec2d0, 0x2, ...})
	/home/runner/work/durabletask-go/durabletask-go/task/executor.go:82 +0x18f
github.com/microsoft/durabletask-go/backend.(*orchestratorProcessor).ProcessWorkItem(0xc0002bac30, {0xd89178, 0xc0002c01c0}, {0xd838c0?, 0xc0003097c0})
	/home/runner/work/durabletask-go/durabletask-go/backend/orchestration.go:83 +0x830
github.com/microsoft/durabletask-go/backend.(*worker).processWorkItem(0xc000287ec0, {0xd89178, 0xc0002c01c0}, {0xd838c0, 0xc0003097c0})
	/home/runner/work/durabletask-go/durabletask-go/backend/worker.go:193 +0x243
created by github.com/microsoft/durabletask-go/backend.(*worker).ProcessNext
	/home/runner/work/durabletask-go/durabletask-go/backend/worker.go:172 +0x565
FAIL	github.com/microsoft/durabletask-go/tests	12.423s
FAILIL
```

**Comment by cgillum** [comment]
This is likely caused by #21
